name = "Prominence II"
author = "Douglas Parker"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba06d928f5aebd136de5a1a7510d7108df7ee597944ce2c217fb9b1d4b226bb0"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
